name: "Grafana Annotation Action"
description: "A GitHub Action to create and automatically create Grafana annotation regions."

inputs:
  grafana_url:
    description: "The base URL of your Grafana instance."
    required: true
  grafana_api_key:
    description: "Grafana API key with write permissions."
    required: true
  message:
    description: "The message for the annotation."
    required: true
  dashboard_id:
    description: "(Optional) The ID of the Grafana dashboard where the annotation should appear."
    required: false
  panel_id:
    description: "(Optional) The ID of a specific panel on the dashboard where the annotation should appear. Requires dashboard_id to be set."
    required: false
  tags:
    description: "(Optional) A comma-separated string of tags for the annotation (e.g., 'tag1,tag2')."
    required: false

outputs:
  annotation_id:
    description: "The ID of the created Grafana annotation."
    value: ${{ steps.main.outputs.annotation_id }}

runs:
  using: "node16" # Specify Node.js 16 runtime
  main: "dist/main/index.js" # This would be main.js bundled into dist/index.js
  post: "dist/post/index.js" # This would be post.js bundled into dist/post.js
